spring:
  kafka:
    consumer:
      enable-auto-commit: true
  application:
    name: practice-wanxiao-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #指定freemarker的模板路径和模板的后缀
  freemarker:
    template-loader-path: classpath:/webapp/
    suffix: .ftl
    # 指定字符集
    charset: utf-8
    # 指定是否要启用缓存
    cache: false
    #指定是否要暴露请求和会话属性
    expose-request-attributes: true
    expose-session-attributes: true
  # 统一 json 格式
  mvc:
    converters:
      preferred-json-mapper: fastJson
mybatis:
  mapperLocations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  typeAliasesPackage: com.wanxiao.practice.model # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true

api:
  boot:
    security:
      basic:
        enabled: true
        path: /swagger-ui.html
    swagger:
      enable: true
      description: API文档
      version: 1.0
      license: ApiBoot
      license-url: http://apiboot.minbox.io/zh-cn/
      contact:
        name: wanxiao